#!/bin/zsh

# LS_COLORS 

LS_COLORS=''
LS_COLORS=$LS_COLORS:'no=0'           # Normal text         
LS_COLORS=$LS_COLORS:'fi=0'           # Regular file          
LS_COLORS=$LS_COLORS:"di=01;34"       # Directory         
LS_COLORS=$LS_COLORS:'ln=00;37'       # Symbolic link     
LS_COLORS=$LS_COLORS:'pi=33'          # Named pipe        
LS_COLORS=$LS_COLORS:'so=01;35'       # Socket            
LS_COLORS=$LS_COLORS:'do=01;35'       # DO                
LS_COLORS=$LS_COLORS:'bd=01;37'       # Block device      
LS_COLORS=$LS_COLORS:'cd=01;37'       # Character device  
LS_COLORS=$LS_COLORS:'ex=35'          # Executable file   
LS_COLORS=$LS_COLORS:'*FAQ=31;7'      # FAQs              
LS_COLORS=$LS_COLORS:'*README=31;7'   # READMEs           
LS_COLORS=$LS_COLORS:'*INSTALL=31;7'  # INSTALLs          
LS_COLORS=$LS_COLORS:'*.sh=47;31'     # Shell-Scripts     
LS_COLORS=$LS_COLORS:'*.zsh=47;31'    # zsh scripts
LS_COLORS=$LS_COLORS:'*.vim=35'       # Vim-"Scripts"     
LS_COLORS=$LS_COLORS:'*.swp=00;44;37' # Swapfiles (Vim)   
LS_COLORS=$LS_COLORS:'*.sl=30;33'     # Slang-Scripts     
LS_COLORS=$LS_COLORS:'*,v=5;34;93'    # Versioncontrols   
LS_COLORS=$LS_COLORS:'or=01;05;31'    # Orphaned link     
LS_COLORS=$LS_COLORS:'*.c=1;33'       # Sources           
LS_COLORS=$LS_COLORS:'*.C=1;33'       # Sources           
LS_COLORS=$LS_COLORS:'*.h=1;33'       # Sources           
LS_COLORS=$LS_COLORS:'*.cc=1;33'      # Sources           
LS_COLORS=$LS_COLORS:'*.cpp=1;33'     # Sources
LS_COLORS=$LS_COLORS:'*.awk=1;33'     # Sources           
LS_COLORS=$LS_COLORS:'*.pl=1;33'      # Sources           
LS_COLORS=$LS_COLORS:'*.jpg=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.jpeg=1;32'    # Images            
LS_COLORS=$LS_COLORS:'*.JPG=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.gif=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.png=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.ppm=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.pgm=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.pbm=1;32'     # Images            
LS_COLORS=$LS_COLORS:'*.tar=01;31'    # Archive 
LS_COLORS=$LS_COLORS:'*.tgz=01;31'    # Archive        
LS_COLORS=$LS_COLORS:'*.gz=01;31'     # Archive           
LS_COLORS=$LS_COLORS:'*.zip=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.rar=01;31'    # Archive
LS_COLORS=$LS_COLORS:'*.sit=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.lha=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.lzh=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.arj=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.bz2=01;31'    # Archive           
LS_COLORS=$LS_COLORS:'*.html=36'      # HTML              
LS_COLORS=$LS_COLORS:'*.htm=1;34'     # HTML              
LS_COLORS=$LS_COLORS:'*.txt=1;34'     # Plain/Text        
LS_COLORS=$LS_COLORS:'*.o=1;36'       # Object-Files      
LS_COLORS=$LS_COLORS:'*.a=1;36'       # Shared-libs       
LS_COLORS=$LS_COLORS:'*.mp3=33;4'
LS_COLORS=$LS_COLORS:'*.ogg=33;4'
LS_COLORS=$LS_COLORS:'*.mpg=35;4'
LS_COLORS=$LS_COLORS:'*.MPG=35;4'
LS_COLORS=$LS_COLORS:'*.mpeg=35;4'
LS_COLORS=$LS_COLORS:'*.avi=35;4'
LS_COLORS=$LS_COLORS:'*.AVI=35;4'
LS_COLORS=$LS_COLORS:'*.wmv=35;4'
LS_COLORS=$LS_COLORS:'*.WMV=35;4'
export LS_COLORS

