#!/bin/zsh

# Completion for some stuff
compctl -g '*.tar.Z *.tar.gz *.tgz *.zip *.ZIP *.tar.bz2' + -g '*' tar xtrct show-archive
compctl -g '*.(gz|z|Z|t[agp]z|tarZ|tz)' + -g '*(-/)' gunzip gzcat zcat
compctl -g '*.(jpg|JPG|jpeg|JPEG|gif|GIF|png|PNG|bmp)' + -g '*(-/)' gimp xv feh
compctl -g '/var/db/pkg/*(/:t)' pkg_delete pkg_info
compctl -g '*.(pdf|PDF)' + -g '*(-/)'  xpdf acroread
compctl -g '[^.]*(-/) *.(c|C|cc|c++|cxx|cpp)' + -f cc CC c++ gcc g++
compctl -g '*.rar' + -g '*(-/) .*(-/)' rar unrar

# Tab host completion for programs  
compctl -k ping telnet ncftp host nslookup irssi rlogin ftp zfanon

# Make completion
compile=(install clean remove uninstall deinstall)
compctl -k compile make
