#!/bin/zsh

# Colors for Prompt
autoload -z colors; colors
autoload -U colors
colors

# set some colors
export red=$'%{\e[0;31m%}'
export RED=$'%{\e[1;31m%}'
export green=$'%{\e[0;32m%}'
export GREEN=$'%{\e[1;32m%}'
export blue=$'%{\e[0;34m%}'
export BLUE=$'%{\e[1;34m%}'
export purple=$'%{\e[0;35m%}'
export PURPLE=$'%{\e[1;35m}'
export cyan=$'%{\e[0;36m%}'
export CYAN=$'%{\e[1;36m%}'
export WHITE=$'%{\e[1;37m%}'
export white=$'%{\e[0;37m%}'
export black=$'%{\e[0;30m%}'
export BLACK=$'%{\e[1;30m%}'
export NC=$'%{\e[0m%}' 
export yellow=$'%{\e[0;33m%}'


if (( EUID == 0 )); then
	PS1=$'${red}%n${BLACK}::${green}%b${green}%m${BLACK}::${WHITE}%20<..<%~ ${BLACK}=>${NC} ';
else 
	PS1=$'${CYAN}%n${BLACK}::${green}%b${green}%m${BLACK}::${WHITE}%20<..<%~ ${BLACK}=>${NC} ';
fi


# *term show current directory
if [ $DISPLAY ]; then
	case $TERM in
		*xterm*|rxvt|rxvt(-unicode|256color)|(E|a|dt)term)
		precmd () {
			print -Pn "\033]0; %n@%m %20<..<%~  \a"
		}
		preexec () {
			print -Pn "\033]0; %n@%m %20<..<%~ <$1> \a"
		}
		unset TMOUT
		;;
	esac
fi
