#!/bin/zsh

# Usefull bindings

bindkey "^E"     end-of-line
bindkey '^[[5~'  history-beginning-search-backward   # Page up 
bindkey '^[[6~'  history-beginning-search-forward    # Page down
bindkey '^[[2~'  overwrite-mode                      # Insert                   
bindkey "^B"     backward-word                       # <STRG> + B
bindkey "^N"     forward-word                        # <STRG> + N
bindkey "^A"     beginning-of-line                   # <STRG> + A
bindkey "^X"     delete-word                         # <STRG> + X
bindkey "^E"     end-of-line			     # <STRG> + E 
bindkey "^Z"     which-command                       # <STRG> + Z
bindkey "^P"     quote-line                          # <STRG> + P
bindkey "^K"      run-help                           # <STRG> + ä
bindkey "^Y" 	 backward-delete-word                # <STRG> + Y
bindkey " " 	 magic-space                         # do history expansion on space
bindkey "\e[3~"  delete-char                         # "Entf" or "Del"
bindkey "^[q"    push-line                           # Kill the *complete* line! (ESC+q)
bindkey "^R" history-incremental-search-backward     # Search in my $HISTFILE (STRG+R)
bindkey "^I" expand-or-complete                      # assimilable to "ls<TAB>"
bindkey "^C" expand-cmd-path                         # $ ls<STRG+E> == /bin/ls
