#!/bin/sh

# Colors for Prompt
autoload -z colors; colors
autoload -U colors
colors

# set some colors
export red=$'%{\e[0;31m%}'
export RED=$'%{\e[1;31m%}'
export green=$'%{\e[0;32m%}'
export GREEN=$'%{\e[1;32m%}'
export blue=$'%{\e[0;34m%}'
export BLUE=$'%{\e[1;34m%}'
export purple=$'%{\e[0;35m%}'
export PURPLE=$'%{\e[1;35m}'
export cyan=$'%{\e[0;36m%}'
export CYAN=$'%{\e[1;36m%}'
export WHITE=$'%{\e[1;37m%}'
export white=$'%{\e[0;37m%}'
export black=$'%{\e[0;30m%}'
export BLACK=$'%{\e[1;30m%}'
export NC=$'%{\e[0m%}' 
export yellow=$'%{\e[0;33m%}'
export YELLOW=$'%{\e[1;33m%}'



function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '±' ${NC} && return
    hg root >/dev/null 2>/dev/null && echo 'Hg' && return
	echo ${white}'> '${NC}


}

function char {

    if [[  $VIMODE == "viins" ]]; then
	echo ${red}'>' ${NC}
    fi
}


function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}

if (( EUID == 0 )) ; then
PROMPT='
%{$red%}%n%{$reset_color%} ${BLACK}at %{$green%}%m%{$reset_color%} ${BLACK}in %{$yellow%}${PWD/#$HOME/~}%{$reset_color%}$(git_prompt_info)
$(virtualenv_info)$(prompt_char) ' 
else
PROMPT='
%{$CYAN%}%n%{$reset_color%} ${BLACK}at %{$green%}%m%{$reset_color%} ${BLACK}in %{$yellow%}${PWD/#$HOME/~}%{$reset_color%}$(git_prompt_info) 
$(virtualenv_info)${VIMODE}$(prompt_char)' 
fi

ZSH_THEME_GIT_PROMPT_PREFIX="${BLACK} on${NC} ${purple}"
ZSH_THEME_GIT_PROMPT_SUFFIX="${reset_color}"
ZSH_THEME_GIT_PROMPT_DIRTY="${green}!"
ZSH_THEME_GIT_PROMPT_UNTRACKED="${green}?"
ZSH_THEME_GIT_PROMPT_CLEAN=""

function zle-line-init zle-keymap-select {
    VIMODE="${${KEYMAP/vicmd/${red}"-"}/(main|viins)/}"
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
